---
title: "marathonWeb"
output: html_document
---



# Tour 2 PAR REGION 


```{r}
setwd("~/a_M1 MIASHS/MARATHON-WEB/Rshiny")
reg <- read.csv2('Presidentielle_Tour_2_region.csv')

reg

```


```{r}
'library(fpp3)
```


```{r}

# Pour LE PEN 
reg_LEPEN <- xtabs(~ Votants, data = reg, subset = Nom == "	LE PEN")
reg_LEPEN
```


```{r}
VOTE= reg$Votants
hist(VOTE,main="nombre de voix",xlab="Nombre de vote pour Macron", ylab="Nb. ind.")

```


```{r}
ville <- reg[reg$Inscrits > 10000, ]

ville
```


```{r}

summary(ville)

```


```{r}
cor(ville)
```


```{r}


library(FactoMineR)
```

```{r}
pca <- PCA(ville, quanti.sup=1)
```


```{r}
ville.clust <- HCPC(pca)

```


```{r}
ville$data.clust
```













# DEPARTEMENT

```{r}
setwd("~/a_M1 MIASHS/MARATHON-WEB/Rshiny")
#'dep <- read.csv2('Presidentielle_Tour_2_dept_clean.csv')
dep <- read.csv2('DEP.csv')
dep
```

```{r}
library(ggplot2)

```






```{r}


mycols <- c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF", "#CC99FF", "#CD534CFF", "#800000", "#CD534CFF", "#000000", "#CD534CFF", "#FFFF00")

ggplot(dep2, aes(x = "Libellé.du.département", y = Votants, fill = Nom)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = Votants, label = Votants), color = "white")+
  scale_fill_manual(values = mycols) +
  theme_void()
```




```{r}
ggplot(data = dep, aes(x="",y=Voix, fill=Nom)) + 
  geom_bar(width=1, stat="identity") +
  coord_polar("y", start=0) 
  #scale_fill_manual
```



```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```
```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

